### ISSUE TITLE
react-navigation 和 dva的结合使用

### ISSUE THREAD

**Issue by shaoting0730** [pheromone/pheromone.github.io#34]
https://pheromone.github.io/2018/07/29/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%AD%A6%E4%B9%A0/dva%E5%92%8Creact-navigation%E7%9A%84%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8/

**Comment by SilenceZhou** [comment]
hahahlkldfj;alj;lfjlas;dfjals;dfjlas;fj
