### ISSUE TITLE
Flutter~国际化教程方案

### ISSUE THREAD

**Issue by shaoting0730** [pheromone/pheromone.github.io#51]
https://pheromone.github.io/2019/06/11/移动端学习/Flutter~国际化教程方案/

**Comment by ZMYBB** [comment]
问题没有得到解决啊 老铁。
flutter: The getter 'appName' was called on null.
flutter: Receiver: null
flutter: Tried calling: appName

**Comment by shaoting0730** [comment]
我并未出现啊.你可以直接下载demo看看.是不是哪里少了?
