### ISSUE TITLE
Android和React Native的简单交互

### ISSUE THREAD

**Issue by shaoting0730** [pheromone/pheromone.github.io#8]
https://pheromone.github.io/2018/03/18/%E5%89%8D%E7%AB%AF%E5%AD%A6%E4%B9%A0/%E9%A9%AC%E8%B5%9B%E5%85%8B%E5%AD%A6%E4%B9%A0/

**Comment by Jasper-zzq** [comment]
是找flutter 资料看到你的博客  你这个马赛克太过分了！！！![:017:](https://pheromone.github.io/imgs/smilies/17.png)![:017:](https://pheromone.github.io/imgs/smilies/17.png)
